version: '3.8'

services:
  backend:
    container_name: back
    build:
      context: .
    volumes:
      - .:/var/www
    ports:
      - "9000:9000"
    networks:
      - product_api_network

  nginx:
    image: nginx:alpine
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    networks:
      - product_api_network

  db:
    image: mysql:8.4
    restart: always
    environment:
      MYSQL_DATABASE: product_api
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - product_api_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: admin
      PMA_PASSWORD: admin
    networks:
      - product_api_network
    depends_on:
      - db

volumes:
  db_data:

networks:
  product_api_network:
    name: product_api_network
